baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[module]
  [module.hugoVersion]
    min = "0.110.0"

[params]
  # Add your theme-specific parameters here

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
