name: Build Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            echo "No lock file found."
          fi

      - name: Install PostCSS CLI
        run: npm install -g postcss-cli

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.127.0'

      - name: Build site
        run: hugo

     
      steps:
         # Reference a specific commit
        - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        # Reference the major version of a release
        - uses: actions/checkout@v4
        # Reference a specific version
        - uses: actions/checkout@v4.2.0
        # Reference a branch
        - uses: actions/checkout@main
