name: Deploy Hugo site to GitHub Pages

on:
  # Runs on pushes targeting the main branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Hugo
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.127.0'
          
      # Install Node.js and npm
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust node version as needed

      # Install PostCSS CLI and other dependencies
      - name: Install PostCSS CLI and dependencies
        run: |
          npm install -g postcss-cli
          npm install  # Install project-specific npm packages if any

      # Build the Hugo site
      - name: Build site
        run: |
          hugo --minify

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Path to Hugo's output directory
          cname: your-custom-domain.com  # Optional: Set a custom domain for GitHub Pages
